apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx
  #namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: rabbitmqcluster
    app.kubernetes.io/component: rabbitmq
     app.kubernetes.io/part-of: rabbitmq
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 15672
      targetPort: 15672
      protocol: TCP
    - name: prometheus
      port: 15692
      targetPort: 15692
      protocol: TCP
    - name: amqp
      port: 5672
      targetPort: 5672
      protocol: TCP
  selector:
    app.kubernetes.io/name: rabbitmqcluster
    #app.kubernetes.io/part-of: ingress-nginx
